#!/usr/bin/env bash
#
# Kill already running process
pid=$(pidof mako)
if [[ pid ]]; then
  kill -9 ${pid}
fi

## launch mako with alt config

CONFIG="$HOME/.config/hypr/mako/config"

pidof mako || mako --config ${CONFIG}
