#!/usr/bin/env bash

## Autostart Programs

signal-desktop &

# Launch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Launch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

