#!/usr/bin/env bash

## Autostart Programs

pidof signal-desktop || signal-desktop &

pidof nm-applet || nm-applet &

pidof hypridle || hypridle &

# Launch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Launch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

