#!/usr/bin/env bash

## launch waybar with alt config

# Kill already running process
pid=$(pidof waybar)
if [[ pid ]]; then
  kill -9 ${pid}
fi

CONFIG="$HOME/.config/hypr/waybar/config.jsonc"
STYLE="$HOME/.config/hypr/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} &
fi
